export const FILTERBYCATEGORY = 'FILTERBYCATEGORY';
export const FILTERBYAREA = 'FILTERBYAREA';
export const SEARCH = 'SEARCH';
export const UPDATEMEALS = 'UPDATEMEALS';
export const GETCATEGORIES = 'GETCATEGORIES';
export const GETAREAS = 'GETAREAS';